<a href="https://colab.research.google.com/github/avs20/DeepLearningHindi/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix multiplication 

In [ ]:
import torch

# tensors 
torch.tensor([[2,3,5],[1,2,9]])


tensor([[2, 3, 5],
        [1, 2, 9]])

In [ ]:
# random values 

torch.rand(2,2)


tensor([[0.6504, 0.2184],
        [0.3873, 0.3832]])

In [ ]:
a = torch.rand((3,5))
print(a.shape)
print(a)


torch.Size([3, 5])
tensor([[0.2235, 0.8796, 0.8028, 0.6795, 0.1912],
        [0.8579, 0.0755, 0.5105, 0.2565, 0.7207],
        [0.7925, 0.0481, 0.4363, 0.1213, 0.5391]])


In [ ]:
a = torch.rand((2,2))
b = torch.rand((2,2))

print(a,b)
# np.dot 
# torch.matmul

torch.matmul(a,b)

tensor([[0.8706, 0.0784],
        [0.7571, 0.1860]]) tensor([[0.1677, 0.4804],
        [0.4394, 0.7717]])


tensor([[0.1805, 0.4788],
        [0.2087, 0.5072]])

In [ ]:
.87 * .16

0.1392

In [ ]:
a * b

tensor([[0.1460, 0.0377],
        [0.3327, 0.1435]])

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
x = torch.rand((3,5))

In [ ]:
print(x)

tensor([[0.2857, 0.3255, 0.7789, 0.7855, 0.1518],
        [0.1040, 0.2476, 0.5401, 0.0728, 0.1194],
        [0.6192, 0.8425, 0.8434, 0.9098, 0.0032]])


In [ ]:
x.numpy()

array([[0.28573233, 0.32548898, 0.77892315, 0.7854549 , 0.15182328],
       [0.10403293, 0.24762446, 0.5400609 , 0.07283103, 0.11941135],
       [0.6191575 , 0.84245336, 0.8433534 , 0.9097687 , 0.00318712]],
      dtype=float32)

In [ ]:
torch.from_numpy(x.numpy())

tensor([[0.2857, 0.3255, 0.7789, 0.7855, 0.1518],
        [0.1040, 0.2476, 0.5401, 0.0728, 0.1194],
        [0.6192, 0.8425, 0.8434, 0.9098, 0.0032]])

In [ ]:
l = [1,2,3,4,5]
torch.tensor(l)

tensor([1, 2, 3, 4, 5])

# Practice 

```
Import PyTorch main library.
Create the variable your_first_tensor and set it to a random torch tensor of size 3 by 3.
Calculate its shape (dimension sizes) and set it to variable tensor_size.
Print the values of your_first_tensor and tensor_size.
```



In [ ]:
# Import torch
____

# Create random tensor of size 3 by 3
your_first_tensor = torch.____(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.____

# Print the values of the tensor and its shape
print(____)
print(____)

```
Create a matrix of ones with shape 3 by 3, and put it on variable tensor_of_ones.
Create an identity matrix with shape 3 by 3, and put it on variable identity_tensor.
Do a matrix multiplication of tensor_of_ones with identity_tensor and print its value.
Do an element-wise multiplication of tensor_of_ones with identity_tensor and print its value.
```


In [ ]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.____(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.____(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.____(tensor_of_ones, ____)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = ____
print(element_multiplication)

### Forward Pass

In [ ]:
import torch 

a = torch.tensor([2])
b = torch.tensor([-4])
c = torch.tensor([-2])
d = torch.tensor([2])

e = a + b
f = c * d 

g = e * f 

print(e, f, g)

tensor([-2]) tensor([-4]) tensor([8])


```
Initialize random tensors x, y and z, each having shape (1000, 1000).
Multiply x with y, putting the result in tensor q.
Do an elementwise multiplication of tensor z with tensor q, putting the results in f
```


In [ ]:
# Initialize tensors x, y and z
x = torch.rand(____, ____)
y = ____
z = ____

# Multiply x with y
q = ____

# Multiply elementwise z with q
f = ____

mean_f = torch.mean(f)
print(mean_f)

### BackProp by auto diff 

In [ ]:
import torch 

x = torch.tensor(-3., requires_grad=True)
y = torch.tensor(5., requires_grad= True)
z = torch.tensor(-2., requires_grad=True)


q = x + y 
f = q * z 

f.backward()

print("gradient of z", str(z.grad))
print("gradient of y", str(y.grad))
print("gradient of x", str(x.grad))

gradient of z tensor(2.)
gradient of y tensor(-2.)
gradient of x ['T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rmul__', '__rpow__', '__rshift__', '__rsub__'

```
Initialize tensors x, y and z to values 4, -3 and 5.
Put the sum of tensors x and y in q, put the product of q and z in f.
Calculate the derivatives of the computational graph.
Print the gradients of the x, y and z tensors.
```


In [ ]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., ____)
y = torch.tensor(____., ____)
z = ____

# Set q to sum of x and y, set f to product of q with z
q = ____
f = ____

# Compute the derivatives
f.____

# Print the gradients
print("Gradient of x is: " + str(____))
print("Gradient of y is: " + str(____))
print("Gradient of z is: " + str(____))

```
Multiply tensors x and y, put the product in tensor q.
Do an elementwise multiplication of tensors z with q.
Calculate the gradients.
```

In [ ]:
x = torch.randn(1000,1000)
y = torch.randn(1000,1000)
z = torch.randn(1000,1000)
# Multiply tensors x and y
q = ____

# Elementwise multiply tensors z with q
f = ____

mean_f = torch.mean(f)

# Calculate the gradients
____

### Intro to Neural Networks

In [ ]:
import torch 

input_layer = torch.rand(10)

w1 = torch.rand(10, 20)
w2 = torch.rand(20,20)
w3 = torch.rand(20, 4)

h1 = torch.matmul(input_layer, w1) 
output = torch.matmul(h2, w3)
print(output)

tensor([270.1283, 314.6077, 293.9081, 265.2788])


### Pytorch way 

In [ ]:
import torch 
import torch.nn as nn 

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__() # calling the super class constructor 
    self.fc1  =  nn.Linear(10,20, bias=False)
    self.fc2  =  nn.Linear(20,20)
    self.output = nn.Linear(20,4)

  def forward(self, X):
    x1 = self.fc1(X)
    x2 = self.fc2(x1)
    x3 = self.output(x2)
    return x3

input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

print(result)




tensor([-0.1085, -0.1558, -0.2881,  0.3149], grad_fn=<AddBackward0>)


In [ ]:
print(net.fc1.bias)

None


Your input will be images of size `(28, 28)`, so images containing 784 pixels. Your network will contain an input_layer (provided for you), a hidden layer with `200 `units, and an output layer with `10` classes. The input layer has already been created for you. You are going to create the weights, and then do matrix multiplications, getting the results from the network.

```
Initialize with random numbers two matrices of weights, called weight_1 and weight_2.
Set the result of input_layer times weight_1 to hidden_1. Set the result of hidden_1 times weight_2 to output_layer.
```

In [ ]:
# Initialize the weights of the neural network
weight_1 = torch.rand(____, ____)
weight_2 = ____

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(____, ____)

# Multiply hidden_1 with weight_2
output_layer = ____
print(output_layer)

You are going to build the same neural network you built in the previous exercise, but now using the PyTorch way. As a reminder, you have 784 units in the input layer, 200 hidden units and 10 units for the output layer.

```
Instantiate two linear layers calling them self.fc1 and self.fc2. Determine their correct dimensions.
Implement the .forward() method, using the two layers you defined and returning x.
```


In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(____, ____)
        self.fc2 = ____

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = ____
        return ____

## Activation functions


In [2]:
import torch 

input_layer = torch.tensor([2., 1.])
weight1 = torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
h1 = torch.matmul(input_layer, weight1)
weight2 = torch.tensor([[0.48, -0.12], [0.64, 0.91]])
output_layer = torch.matmul(h1, weight2)
print(output_layer)

tensor([0.9696, 0.7527])


In [3]:
weight = torch.matmul(weight1, weight2)
output = torch.matmul(input_layer, weight)
print(weight)
print(output_layer)

tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])
tensor([0.9696, 0.7527])


ReLU in torch 

In [4]:
import torch.nn as nn 

relu = nn.ReLU()

tensor1 = torch.tensor([2., -4.])

print(relu(tensor1))

tensor([2., 0.])


In [6]:
import torch.nn as nn 

relu = nn.ReLU()

tensor2 = torch.tensor([[2., -4.], [1.2, 0]])

print(relu(tensor2))

tensor([[2.0000, 0.0000],
        [1.2000, 0.0000]])


Neural networks

Let us see the differences between neural networks which apply ReLU and those which do not apply ReLU. We have already initialized the input called input_layer, and three sets of weights, called weight_1, weight_2 and weight_3.

We are going to convince ourselves that networks with multiple layers which do not contain non-linearity can be expressed as neural networks with one layer.

The network and the shape of layers and weights is shown below.

```
Calculate the first and second hidden layer by multiplying the appropriate inputs with the corresponding weights.
Calculate and print the results of the output.
Set weight_composed_1 to the product of weight_1 with weight_2, then set weight to the product of weight_composed_1 with weight_3.
Calculate and print the output.
```


In [ ]:
# Calculate the first and second hidden layer
hidden_1 = torch.matmul(____, ____)
hidden_2 = torch.matmul(____, ____)

# Calculate the output
print(torch.matmul(____, ____))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(____, ____)
weight = torch.matmul(____, ____)

# Multiply input_layer with weight
print(torch.matmul(____, ____))

ReLU activation

In this exercise, we have the same settings as the previous exercise. But now we are going to build a neural network which has non-linearity. By doing so, we are going to convince ourselves that networks with multiple layers and non-linearity functions cannot be expressed as a neural network with one layer.

```
Apply the non-linearity to the two hidden layers and print the result.
Apply the non-linearity to the product of first two weights.
Multiply the result of the previous step with weight_3.
Multiply input_layer with weight and print the results
```


In [ ]:
# Instantiate non-linearity
relu = nn.ReLU()

# Apply non-linearity on the hidden layers
hidden_1_activated = ____(torch.matmul(input_layer, weight_1))
hidden_2_activated = ____(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = ____(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(____, ____)

# Multiply input_layer with weight
print(torch.matmul(____, ____))

### Loss Functions

In [7]:
logits =  torch.tensor([[3.2, 5.1, -1.7]])
ground_truth = torch.tensor([0])

#loss function 
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)

print(loss)


tensor(2.0404)


In [8]:
logits = torch.tensor([[10.2, 5.1, -1.7]])

loss = criterion(logits, ground_truth)

print(loss)

tensor(0.0061)


In [9]:
logits = torch.tensor([[-10.2, 5.1, -1.7]])

loss = criterion(logits, ground_truth)

print(loss)

tensor(15.3011)


```
Initialize the tensor of scores with numbers [[-1.2, 0.12, 4.8]], and the tensor of ground truth [2].
Instantiate the cross-entropy loss and call it criterion.
Compute and print the loss.
```


In [ ]:
# Initialize the scores and ground truth
logits = ____
ground_truth = ____

# Instantiate cross entropy loss
criterion = nn.____

# Compute and print the loss
loss = ____
print(____)

Loss function of random scores

If the neural network predicts random scores, what would be its loss function? Let's find it out in PyTorch. The neural network is going to have 1000 classes, each having a random score. For ground truth, it will have class 111. Calculate the loss function.

```
Import torch and torch.nn as nn
Initialize logits with a random tensor of shape (1, 1000) and ground_truth with a tensor containing the number 111.
Instantiate the cross-entropy loss in a variable called criterion.
Calculate and print the loss function.
```


### Data loaders

In [10]:
import torch 
import torchvision
import torch.utils.data 
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.48216, 0.44543),
                          (0.24703, 0.24349, 0.26519))])



trainset = torchvision.datasets.CIFAR10(root="./data", train = True, download = True, transform = transform)
testset = torchvision.datasets.CIFAR10(root="./data", train = False, download = True, transform = transform)


trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle = True, num_workers = 4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle = False, num_workers = 4)


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [11]:
# dataloader 

print(testloader.dataset.data.shape)

(10000, 32, 32, 3)


Preparing MNIST dataset

You are going to prepare dataloaders for MNIST training and testing set. As we explained in the lecture, MNIST has some differences to CIFAR-10, with the main difference being that MNIST images are grayscale (1 channel based) instead of RGB (3 channels).

```
Transform the data to torch tensors and normalize it to have mean is 0.1307 and std is 0.3081.
Prepare the trainset and the testset.
Prepare the dataloaders for training and testing so that only 32 pictures are processed at a time and the training data is shuffled each time.
```

In [ ]:
# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.____,
								transforms.____((____), ((____)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST('mnist', train=____, 
									  download=____, transform=____)
testset = ____('mnist', ____,
			   ____, ____)

# Prepare training loader and testing loader
trainloader = torch.utils.data.DataLoader(____, ____,
                                          ____, num_workers=0)
testloader = torch.utils.data.DataLoader(____, ____,
										 ____, num_workers=0) 

Inspecting the dataloaders

Now you are going to explore a bit the dataloaders you created in the previous exercise. In particular, you will compute the shape of the dataset in addition to the minibatch size.

```
Find the shapes of the trainset and testset.
Print the computed values.
Find the size of the minibatch for both trainset and testset.
Print the minibatch size.
```

In [ ]:
# Compute the shape of the training set and testing set
trainset_shape = ____.____.____.____
testset_shape = ____.____.____.____

# Print the computed shapes
print(____, ____)

# Compute the size of the minibatch for training set and testing set
trainset_batchsize = ____.____
testset_batchsize = ____.____

# Print sizes of the minibatch
print(____, ____)

### Training a neural network

Build a class for a neural network which will be used to train on the MNIST dataset. The dataset contains images of shape (28, 28, 1), so you should deduct the size of the input layer. For hidden layer use 200 units, while for output layer use 10 units (1 for each class). For activation function, use relu in a functional way (nn.Functional is already imported as F).

For context, the same net will be trained and used to make predictions in the next two exercises.

```
Define the class called Net which inherits from nn.Module.
In the __init__() method, define the parameters for the two fully connected layers.
In the .forward() method, do the forward step.
```


In [ ]:
# Define the class Net
____:
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(____ * ____ * ____, ____)
        self.fc2 = ____

    def forward(self, x):   
    	# Do the forward pass
        x = F.relu(self.fc1(____))
        x = self.____(____)
        return ____

Given the fully connected neural network (called model) which you built in the previous exercise and a train loader called train_loader containing the MNIST dataset (which we created for you), you're to train the net in order to predict the classes of digits. You will use the Adam optimizer to optimize the network, and considering that this is a classification problem you are going to use cross entropy as loss function.

```
Instantiate the Adam optimizer with learning rate 3e-4 and instantiate Cross-Entropy as loss function.
Complete a forward pass on the neural network using the input data.
Using backpropagation, compute the gradients of the weights, and then change the weights using the Adam optimizer.
```


In [ ]:
# do not change
train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('./data/', train=True, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_train, shuffle=True)

test_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/data/', train=False, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_test, shuffle=True)

In [ ]:
# Instantiate the Adam optimizer and Cross-Entropy loss function
model = Net()   
optimizer = optim.Adam(____.parameters(), lr=3e-4)
criterion = nn.____
  
for batch_idx, data_target in enumerate(train_loader):
    data = data_target[0]
    target = data_target[1]
    data = data.view(-1, 28 * 28)
    optimizer.zero_grad()

    # Complete a forward pass
    output = model(____)

    # Compute the loss, gradients and change the weights
    loss = ____
    loss.____
    optimizer.____

Using the network to make predictions

Now that you have trained the network, use it to make predictions for the data in the testing set. The network is called model (same as in the previous exercise), and the loader is called test_loader. We have already initialized variables total and correct to 0.

```
Set the network in testing (eval) mode.
Put each image into a vector using inputs.view(-1, number_of_features) where the number of features should be deducted by multiplying spatial dimensions (shape) of the image.
Do the forward pass and put the predictions in output variable.
```


In [ ]:
# Set the model in eval mode
model.____

for i, data in enumerate(test_loader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    inputs = inputs.view(-1, ____)
    
    # Do the forward pass and get the predictions
    outputs = ____
    _, outputs = torch.max(____.data, ____)
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))